version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: bundle install

  test:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: bundle install
      - run:
          name: tests
          command: bundle exec rspec
      - run:
          name: rubocop
          command: bundle exec rubocop

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
